#!/bin/bash
#PBS -l nodes=2:ppn=4
#PBS -l walltime=00:10:00
#PBS -N Ex3
#PBS -j oe
#PBS -o log.${PBS_JOBID}
#PBS -m abe 

echo '-------------------------------'
cd $PBS_O_WORKDIR
echo $PBS_O_WORKDIR
echo Running on host $(hostname)
echo Time is $(date)
echo PBS_NODEFILE is $(cat $PBS_NODEFILE)
echo '-------------------------------'
echo -e '\n\n'

module load openmpi/gcc/1.6.5/ 

mpirun Rscript ./ex3.R 10
