#!/usr/bin/env bash
#PBS -l nodes=1:ppn=4
#PBS -l walltime=00:10:00
#PBS -N Ex7
#PBS -j oe
#PBS -o log.${PBS_JOBID}
#PBS -m abe 

echo '-------------------------------'
cd $PBS_O_WORKDIR
echo $PBS_O_WORKDIR
echo Running on host $(hostname)
echo Time is $(date)
echo PBS_NODEFILE is $(cat $PBS_NODEFILE)
echo '-------------------------------'
echo -e '\n\n'

export TOTALPROCS=$(cat ${PBS_NODEFILE} | wc -l)

Rscript ./ex7.R